---
abstract: 'OpenTracing APM support for DBI-based database interaction'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  DBD::SQLite: '0'
  DBI: '0'
  Email::Sender::Transport::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Any::Adapter: '0'
  OpenTracing::Any: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '0'
  Test::More: '0.98'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OpenTracing-Integration-DBI
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  OpenTracing::Integration::DBI:
    file: lib/OpenTracing/Integration/DBI.pm
    version: '0.001'
requires:
  Class::Method::Modifiers: '0'
  DBI: '0'
  Log::Any: '0'
  OpenTracing: '1.001'
  OpenTracing::DSL: '0'
  OpenTracing::Integration: '0'
  Role::Tiny::With: '0'
  Syntax::Keyword::Try: '0'
  indirect: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/OpenTracing-Integration-DBI/issues
  homepage: https://github.com/team-at-cpan/OpenTracing-Integration-DBI
  repository: https://github.com/team-at-cpan/OpenTracing-Integration-DBI.git
version: '0.001'
x_authority: cpan:TEAM
x_generated_by_perl: v5.30.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
